In [2]:
### Imports
import pandas as pd
import numpy as np
import os

In [3]:
# get working directory
#wd = os.path.dirname(os.getcwd())
# wd = "N:\MASTER_DS\Code\Kaggle_competition\Kaggle-seminar\student-performance"
wd = "D:\\"
os.chdir(wd)
print("Working Directory: ", os.getcwd())

Working Directory:  D:\

In [4]:
dtypes={
    'level': np.uint8,  
    'session_id':np.int64,
    'level_group':'category',
    'event_name':np.int64,
    'name':np.int64,
    'fqid':np.int64,
    'room_fqid':np.int64,
    'text_fqid':np.int64,
    'fullscreen':'category',
    'hq':'category',
    'music':'category',
    'hover_duration_mean':np.float32,
    'difference_clicks_mean':np.float64,
    'elapsed_time_std':np.float64,
    'page_std':np.float64,
    'room_coor_x_std':np.float64,
    'room_coor_y_std':np.float64,
    'screen_coor_x_std':np.float64,
    'screen_coor_y_std':np.float64,
    'hover_duration_std':np.float64,
    'difference_clicks_std':np.float64,
    'index_sum_of_actions':np.int32,
    'difference_clicks_max':np.float64,
    'elapsed_time_max':np.float64,
    'clicks_per_second':np.float64}

In [5]:
import pandas as pd

group_size = 100  # Anzahl der Gruppen pro Batch
dataframes = []

# Manuell Batches lesen und verarbeiten
with open('deine_datei.csv', 'r') as file:
    header = file.readline()  # Überspringe die Header-Zeile
    batch = []
    current_group = None
    for line in file:
        group_index = int(line.split(',')[0])  # Annahme: Der Gruppenindex befindet sich in der ersten Spalte
        if current_group is None:
            current_group = group_index

        if group_index != current_group or len(batch) >= group_size:
            # Erstelle ein DataFrame aus dem aktuellen Batch
            df = pd.read_csv(pd.compat.StringIO(''.join(batch)))
            dataframes.append(df)
            batch = []
            current_group = group_index

        batch.append(line)

    # Verarbeite den letzten unvollständigen Batch
    if batch:
        df = pd.read_csv(pd.compat.StringIO(''.join(batch)))
        dataframes.append(df)

# Verarbeite die einzelnen Batches
for df in dataframes:
    # Führe hier die gewünschten Operationen mit jedem Batch durch
    # ...

SyntaxError: incomplete input (1004198672.py, line 33)

In [6]:
dataset_df = pd.read_csv('data/processed/df_added_variables.csv',nrows=200000)#, dtype=dtypes)

In [7]:
dataset_df.head()

,Unnamed: 0,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,...,room_fqid,text_fqid,fullscreen,hq,music,level_group,difference_clicks,screen_distance_clicks,distance_clicks,sum_distance_clicks
0,0,20090312431273200,0,0.000,cutscene_click,basic,0,NaN,-413.9914,-159.31468,...,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4,0.000,NaN,0.0,0.0
1,1,20090312431273200,2,0.831,person_click,basic,0,NaN,-413.9914,-159.31468,...,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,0.831,0.0,0.0,0.0
2,2,20090312431273200,3,1.147,person_click,basic,0,NaN,-413.9914,-159.31468,...,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,0.316,0.0,0.0,0.0
3,3,20090312431273200,1,1.323,person_click,basic,0,NaN,-413.9914,-159.31468,...,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,0.176,0.0,0.0,0.0
4,4,20090312431273200,4,1.863,person_click,basic,0,NaN,-412.9914,-159.31468,...,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4,0.540,1.0,1.0,1.0